version: "3.9"
services:
  bus-webapp-backend:
    build: .
    ports:
      - "8080:8080"
    container_name: "bus-webapp-backend"
    volumes:
      - ./app:/app
    networks:
      - br0

  bus-webapp-db:
    image: mariadb:latest
    container_name: "bus-webapp-db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bus_webapp
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_pass
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - br0
    secrets:
      - db_pass

networks:
  br0:
    driver: bridge

secrets:
  db_pass:
    file: ./secrets/db_pass
